set correct timezone to satisfy Solr's locking mechanism
This fixes this error:

2017-04-27 14:20:53.863 ERROR (coreLoadExecutor-6-thread-1) [   x:nice2_index] o.a.s.u.SolrIndexWriter Error closing IndexWriter
org.apache.lucene.store.AlreadyClosedException: Underlying file changed by an external force at 2017-04-27T14:20:53.751626Z, (lock=NativeFSLock(path=/persist/index_data/index/write
.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2017-04-27T14:20:53.753933Z))